# Generated by Django 3.1.2 on 2020-10-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forStudents', '0004_auto_20201022_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
